name: "GCP docker registry login"
description: "Login to the GCP docker registry"
outputs:
  registry:
    description: "The full name of the registry we logged into"
    value: ${{ format('us-east1-docker.pkg.dev/firezone-staging') }}
runs:
  using: "composite"
  steps:
    - id: auth1
      uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
      continue-on-error: true
      with:
        token_format: access_token
        workload_identity_provider: "projects/397012414171/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
        service_account: "github-actions@github-iam-387915.iam.gserviceaccount.com"
        export_environment_variables: true
        create_credentials_file: true

    - id: auth2
      if: ${{ steps.auth1.conclusion == 'failure' }}
      uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
      continue-on-error: true
      with:
        token_format: access_token
        workload_identity_provider: "projects/397012414171/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
        service_account: "github-actions@github-iam-387915.iam.gserviceaccount.com"
        export_environment_variables: true
        create_credentials_file: true

    - id: auth3
      if: ${{ steps.auth2.conclusion == 'failure' }}
      uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
      with:
        token_format: access_token
        workload_identity_provider: "projects/397012414171/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
        service_account: "github-actions@github-iam-387915.iam.gserviceaccount.com"
        export_environment_variables: true
        create_credentials_file: true

    - name: Login to Google Artifact Registry
      if: ${{ runner.os == 'Linux' }}
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: "us-east1-docker.pkg.dev"
        username: oauth2accesstoken
        password: ${{ steps.auth3.outputs.access_token || steps.auth2.outputs.access_token || steps.auth1.outputs.access_token }}

    # DockerHub has stupid rate limits (see https://www.docker.com/increase-rate-limits/)
    # Use Google's public mirror instead: https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images
    - name: Setup registry mirror
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        # Create daemon.json if it doesn't exist
        if [ ! -f /etc/docker/daemon.json ]; then
          echo '{}' | sudo tee /etc/docker/daemon.json > /dev/null
        fi

        # Add or update registry-mirrors configuration
        echo "$(jq '. += { "registry-mirrors": ["https://mirror.gcr.io"] }' /etc/docker/daemon.json)" > new_daemon.json
        sudo mv new_daemon.json /etc/docker/daemon.json
        sudo service docker restart

    - name: Print docker system info
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: docker system info
