name: Setup musl toolchain
description: Install musl toolchain for cross-compilation based on the target triple
inputs:
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-musl, aarch64-unknown-linux-musl, armv7-unknown-linux-musleabihf)'
    required: true
runs:
  using: composite
  steps:
    - name: Setup musl for x86_64
      if: ${{ inputs.target == 'x86_64-unknown-linux-musl' }}
      shell: bash
      run: |
        sudo apt-get install musl-tools

    - name: Setup musl for aarch64
      if: ${{ inputs.target == 'aarch64-unknown-linux-musl' }}
      shell: bash
      run: |
        # TODO: musl.cc has blocked GitHub actions: https://github.com/orgs/community/discussions/27906
        # Find some other way to keep these updated.
        if [[ ! -x /tmp/toolchain/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc ]]; then
          curl -fsSL https://github.com/firezone/musl-toolchains/releases/download/1/aarch64-linux-musl-cross.tgz -o /tmp/aarch64-linux-musl-cross.tgz
          mkdir -p /tmp/toolchain
          tar -xzf /tmp/aarch64-linux-musl-cross.tgz -C /tmp/toolchain
        fi

        CC=/tmp/toolchain/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc

        echo "CC_aarch64_unknown_linux_musl=$CC" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=$CC" >> $GITHUB_ENV

    - name: Setup musl for armv7
      if: ${{ inputs.target == 'armv7-unknown-linux-musleabihf' }}
      shell: bash
      run: |
        # TODO: musl.cc has blocked GitHub actions: https://github.com/orgs/community/discussions/27906
        # Find some other way to keep these updated.
        if [[ ! -x /tmp/toolchain/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc ]]; then
          curl -fsSL https://github.com/firezone/musl-toolchains/releases/download/1/arm-linux-musleabihf-cross.tgz -o /tmp/arm-linux-musleabihf-cross.tgz
          mkdir -p /tmp/toolchain
          tar -xzf /tmp/arm-linux-musleabihf-cross.tgz -C /tmp/toolchain
        fi

        CC=/tmp/toolchain/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc

        echo "CC_armv7_unknown_linux_musleabihf=$CC" >> $GITHUB_ENV
        echo "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER=$CC" >> $GITHUB_ENV
