---
name: "Setup Rust `target` dir caching"
description: "Sets up caching for the Rust `target` directory"
inputs:
  key:
    description: "Additional cache key"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # Restore mtime for all files to avoid re-builds if they haven't changed.
    # This requires `fetch-depth: 0` on the checkout action!
    - uses: chetan/git-restore-mtime-action@bca85c11349c76b2dbac06d07edf6c2407dbab1e # v2.2

    - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      with:
        workspaces: rust
        cache-targets: true
        cache-workspace-crates: true
        key: ${{ inputs.key }}
        prefix-key: v2-rust
        save-if: ${{ github.ref == 'refs/heads/main' }} # Only save on main
