---
name: "Setup Rust `target` dir caching"
description: "Sets up caching for the Rust `target` directory"
inputs:
  key:
    description: "Additional cache key"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      with:
        workspaces: rust
        cache-targets: true
        cache-all-crates: true
        cache-workspace-crates: true
        key: ${{ inputs.key }}
        # save-if: ${{ github.ref == 'refs/heads/main' }} # Only save on main
