#[derive(Clone, Copy)]
pub enum ResourceEditPath {
    DnsAddress,
    DnsName,
    DnsAddressDescription,
    DnsSites,
    DnsIpStack,
    DnsFilters,
    CidrAddress,
    CidrName,
    CidrAddressDescription,
    CidrSites,
    CidrFilters,
    StaticDevicePoolName,
    StaticDevicePoolDevices,
    StaticDevicePoolFilters,
    DynamicDevicePoolName,
    DynamicDevicePoolAddress,
    DynamicDevicePoolFilters,
    DnsToCidr,
    DnsToStaticDevicePool,
    DnsToDynamicDevicePool,
    CidrToDns,
    CidrToStaticDevicePool,
    CidrToDynamicDevicePool,
    StaticDevicePoolToDns,
    StaticDevicePoolToCidr,
    StaticDevicePoolToDynamicDevicePool,
    DynamicDevicePoolToDns,
    DynamicDevicePoolToCidr,
    DynamicDevicePoolToStaticDevicePool,
}

impl ResourceEditPath {
    #[inline(never)]
    pub fn mark_covered(self) {
        match self {
            Self::DnsAddress => std::hint::black_box(0_u8),
            Self::DnsName => std::hint::black_box(1_u8),
            Self::DnsAddressDescription => std::hint::black_box(2_u8),
            Self::DnsSites => std::hint::black_box(3_u8),
            Self::DnsIpStack => std::hint::black_box(4_u8),
            Self::DnsFilters => std::hint::black_box(5_u8),
            Self::CidrAddress => std::hint::black_box(6_u8),
            Self::CidrName => std::hint::black_box(7_u8),
            Self::CidrAddressDescription => std::hint::black_box(8_u8),
            Self::CidrSites => std::hint::black_box(9_u8),
            Self::CidrFilters => std::hint::black_box(10_u8),
            Self::StaticDevicePoolName => std::hint::black_box(11_u8),
            Self::StaticDevicePoolDevices => std::hint::black_box(12_u8),
            Self::StaticDevicePoolFilters => std::hint::black_box(13_u8),
            Self::DynamicDevicePoolName => std::hint::black_box(14_u8),
            Self::DynamicDevicePoolAddress => std::hint::black_box(15_u8),
            Self::DynamicDevicePoolFilters => std::hint::black_box(16_u8),
            Self::DnsToCidr => std::hint::black_box(17_u8),
            Self::DnsToStaticDevicePool => std::hint::black_box(18_u8),
            Self::DnsToDynamicDevicePool => std::hint::black_box(19_u8),
            Self::CidrToDns => std::hint::black_box(20_u8),
            Self::CidrToStaticDevicePool => std::hint::black_box(21_u8),
            Self::CidrToDynamicDevicePool => std::hint::black_box(22_u8),
            Self::StaticDevicePoolToDns => std::hint::black_box(23_u8),
            Self::StaticDevicePoolToCidr => std::hint::black_box(24_u8),
            Self::StaticDevicePoolToDynamicDevicePool => std::hint::black_box(25_u8),
            Self::DynamicDevicePoolToDns => std::hint::black_box(26_u8),
            Self::DynamicDevicePoolToCidr => std::hint::black_box(27_u8),
            Self::DynamicDevicePoolToStaticDevicePool => std::hint::black_box(28_u8),
        };
    }
}
