name: "Setup Rust"
description: "Sets up the correct Rust version and caching via sccache and a GCP backend"
inputs:
  cache_backend:
    description: "Choose between sccache or github"
    required: false
    default: 'sccache'
  targets:
    description: "Additional targets to install"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # Setup sccache, works well for most Rust components
    - if: ${{ inputs.cache_backend == 'sccache' }}
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/397012414171/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions"
        service_account: "github-actions@github-iam-387915.iam.gserviceaccount.com"
        export_environment_variables: true
        create_credentials_file: true
    - if: ${{ inputs.cache_backend == 'sccache' }}
      run: |
        echo "SCCACHE_GCS_BUCKET=firezone-staging-sccache" >> $GITHUB_ENV
        echo "SCCACHE_GCS_RW_MODE=READ_WRITE" >> $GITHUB_ENV
      shell: bash
    - if: ${{ inputs.cache_backend == 'sccache' }}
      uses: mozilla-actions/sccache-action@v0.0.4
    - if: ${{ inputs.cache_backend == 'sccache' }}
      run: echo "RUSTC_WRAPPER=$SCCACHE_PATH" >> $GITHUB_ENV
      shell: bash

    # Setup GH actions cache, works better for Tauri clients and some libs
    - if: ${{ inputs.cache_backend == 'github' }}
      uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref_name == 'main' }}
        key: ${{ runner.os }}-${{ inputs.targets }}
        workspaces: ./rust

    # Common to either cache backend
    - name: Extract Rust version
      run: |
        RUST_TOOLCHAIN=$(grep 'channel' rust-toolchain.toml | awk -F '"' '{print $2}')
        echo "RUST_TOOLCHAIN=$RUST_TOOLCHAIN" >> $GITHUB_ENV
      shell: bash
      working-directory: ./rust
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.RUST_TOOLCHAIN }}
        components: rustfmt,clippy
    - if: inputs.targets != ''
      run: rustup target add ${{ inputs.targets }}
      shell: bash

    # Start sccache
    - if: ${{ inputs.cache_backend == 'sccache' }}
      name: Start sccache
      run: $SCCACHE_PATH --start-server
      shell: bash
