name: "Setup Node"
description: "Sets up the correct Node version and installs pnpm"
inputs:
  lockfile-dir:
    description: "Path to the pnpm-lock.yaml file"
    required: true
  npmjs-token:
    description: "NPMJS token to use for authentication"
    required: true
  node-version:
    description: "Version of nodejs to install"
    required: false
    default: "22"
runs:
  using: "composite"
  steps:
    - name: Configure npm auth
      shell: bash
      run: |
        if [[ -z "${{ inputs.npmjs-token }}" ]]; then
          echo "inputs.npmjs-token not provided" >&2
          exit 1
        fi
        cat > "$HOME/.npmrc" <<'RC'
        always-auth=true
        //registry.npmjs.org/:_authToken=${{ inputs.npmjs-token }}
        RC
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: latest
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: ${{ inputs.lockfile-dir }}
