name: "Setup Node"
description: "Sets up the correct Node version and installs pnpm"
inputs:
  node-version:
    description: "Version of nodejs to install"
    required: false
    default: "20"
runs:
  using: "composite"
  steps:
    - name: Configure npm auth
      shell: bash
      env:
        NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      run: |
        if [[ -z "${NPMJS_TOKEN}" ]]; then
          echo "NPMJS_TOKEN is not set. Add it as a repo/org secret." >&2
          exit 1
        fi
        cat > "$HOME/.npmrc" <<'RC'
        always-auth=true
        //registry.npmjs.org/:_authToken=${NPMJS_TOKEN}
        RC
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: latest
