name: "Setup Node"
description: "Sets up the correct Node version and installs pnpm"
inputs:
  node-version:
    description: "Version of nodejs to install"
    required: false
    default: "20"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 9.3
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
