use std::{fmt, future::Future, sync::LazyLock, time::Duration};

use async_trait::async_trait;
use bytes::Bytes;
use http::{Request, Response};
use opentelemetry_http::{HttpClient, HttpError};
use opentelemetry_otlp::{MetricExporter, Protocol, WithExportConfig as _, WithHttpConfig as _};
use opentelemetry_sdk::{
    error::OTelSdkResult,
    metrics::{Temporality, data::ResourceMetrics, exporter::PushMetricExporter},
};

use crate::{Env, feature_flags, ingest};

/// Hostnames of Firezone's hosted OTLP metrics ingest endpoints.
const INGEST_HOST_PROD: &str = "otlp.firezone.dev";
const INGEST_HOST_STAGING: &str = "otlp.firez.one";

/// Write-only ingest keys embedded in the endpoint path, analogous to the PostHog
/// project keys: shipping them in the client is safe because they only permit
/// writing metrics, never reading them.
// TODO: replace with the keys generated by the `azure-*-telemetry` workspaces once
// the stacks are applied. The production endpoint is not deployed yet.
const INGEST_KEY_PROD: &str = "REPLACE_WITH_PROD_INGEST_KEY";
const INGEST_KEY_STAGING: &str = "REPLACE_WITH_STAGING_INGEST_KEY";

static CLIENT_PROD: LazyLock<ingest::Client> =
    LazyLock::new(|| ingest::Client::new(INGEST_HOST_PROD));
static CLIENT_STAGING: LazyLock<ingest::Client> =
    LazyLock::new(|| ingest::Client::new(INGEST_HOST_STAGING));

/// Builds a metric exporter for Firezone's hosted OTLP endpoint for `env`, or
/// `None` for environments without a hosted endpoint.
///
/// Telemetry is sent over the tunnel-bypassing [`ingest::Client`], and the exporter
/// only emits while the `stream_metrics` feature flag is enabled.
pub(crate) fn metric_exporter(env: Env) -> Option<impl PushMetricExporter> {
    let (host, key, client) = match env {
        Env::Production => (INGEST_HOST_PROD, INGEST_KEY_PROD, &*CLIENT_PROD),
        Env::Staging => (INGEST_HOST_STAGING, INGEST_KEY_STAGING, &*CLIENT_STAGING),
        Env::Entrypoint | Env::OnPrem | Env::DockerCompose | Env::Localhost => return None,
    };

    // A programmatically-set endpoint is used verbatim (the SDK does not append the
    // signal path), so the full `/v1/metrics` path is spelled out here. The key
    // prefix is validated and stripped by the edge before the collector sees it.
    let inner = MetricExporter::builder()
        .with_http()
        .with_http_client(IngestHttpClient(client))
        .with_protocol(Protocol::HttpBinary)
        .with_endpoint(format!("https://{host}/{key}/v1/metrics"))
        .build()
        .inspect_err(|e| tracing::debug!("Failed to build hosted OTLP metric exporter: {e:#}"))
        .ok()?;

    Some(StreamMetricsGated(inner))
}

/// Bridges the OTLP/HTTP exporter onto the tunnel-bypassing [`ingest::Client`] so
/// metrics never loop back through connlib.
struct IngestHttpClient(&'static ingest::Client);

#[async_trait]
impl HttpClient for IngestHttpClient {
    async fn send_bytes(&self, request: Request<Bytes>) -> Result<Response<Bytes>, HttpError> {
        self.0.send_request(request).await.map_err(Into::into)
    }
}

impl fmt::Debug for IngestHttpClient {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("IngestHttpClient").finish()
    }
}

/// Wraps a [`PushMetricExporter`] so it only exports while `stream_metrics` is on.
///
/// The flag is checked once per export interval, so toggling it at runtime takes
/// effect without rebuilding the meter provider.
struct StreamMetricsGated<E>(E);

impl<E> PushMetricExporter for StreamMetricsGated<E>
where
    E: PushMetricExporter,
{
    fn export(&self, metrics: &ResourceMetrics) -> impl Future<Output = OTelSdkResult> + Send {
        async move {
            if !feature_flags::stream_metrics() {
                return Ok(());
            }

            self.0.export(metrics).await
        }
    }

    fn force_flush(&self) -> OTelSdkResult {
        self.0.force_flush()
    }

    fn shutdown(&self) -> OTelSdkResult {
        self.0.shutdown()
    }

    fn shutdown_with_timeout(&self, timeout: Duration) -> OTelSdkResult {
        self.0.shutdown_with_timeout(timeout)
    }

    fn temporality(&self) -> Temporality {
        self.0.temporality()
    }
}
