tag-prefix: "android-client-"
template: >
  README: HAVE YOU SENT THE CLIENT FOR REVIEW AND HAVE THEY BEEN ACCEPTED?
  DO NOT PUBLISH THIS RELEASE UNTIL THAT IS DONE.

  Please see our
  [changelog](https://www.firezone.dev/changelog?utm_source=github-releases)
  for more details.
