//! Per-launch cookie + advisory file lock for GUI first-instance detection.
//!
//! The first GUI instance acquires an exclusive non-blocking advisory lock
//! on `<known_dirs::session()>/launch-cookie` and writes a fresh 32-byte
//! random cookie into it. The lock is held for the lifetime of the
//! process. Subsequent launches can't take the lock, so they read the
//! cookie out of the file and use it to authenticate IPC traffic to the
//! already-running instance.
//!
//! The cookie binds an IPC connection to a specific *launch generation*.
//! After a graceful shutdown or a crash the kernel auto-releases the
//! file lock, a fresh launch becomes the new first instance, and the
//! cookie file is overwritten under the new exclusive lock. Any
//! connection from a process that read the stale cookie before the
//! crash-restart cycle is rejected.
//!
//! The cookie is **not** a same-user secret — a hostile same-user
//! process can read the file directly. The real identity check is the
//! pipe DACL on Windows (kernel-tracked package SID) and the socket
//! filesystem permissions on Linux. The cookie is the freshness glue
//! across launches.

use anyhow::{Context, Result};
use fd_lock::{RwLock as FdRwLock, RwLockWriteGuard as FdRwLockWriteGuard};
use std::{
    fs::{File, OpenOptions},
    io::{Read, Seek, SeekFrom, Write},
    path::PathBuf,
};

/// Wire size of the launch cookie. 256 bits of randomness.
const COOKIE_LEN: usize = 32;

/// Random cookie generated by the first instance on launch and
/// shared with subsequent instances via a user-private file.
#[derive(Clone, Copy, serde::Deserialize, serde::Serialize)]
pub struct LaunchCookie([u8; COOKIE_LEN]);

impl LaunchCookie {
    pub fn random() -> Self {
        Self(rand::random())
    }

    #[cfg(test)]
    pub fn new(bytes: [u8; COOKIE_LEN]) -> Self {
        Self(bytes)
    }

    pub fn as_bytes(&self) -> &[u8; COOKIE_LEN] {
        &self.0
    }
}

impl PartialEq for LaunchCookie {
    /// Constant-time compare via [`subtle::ConstantTimeEq`]. The threat
    /// model doesn't expose timing oracles to a network attacker, but
    /// `ct_eq` is cheap insurance against future changes.
    fn eq(&self, other: &Self) -> bool {
        use subtle::ConstantTimeEq as _;
        self.0.ct_eq(&other.0).into()
    }
}

impl Eq for LaunchCookie {}

impl std::fmt::Debug for LaunchCookie {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Don't accidentally log the cookie. Both halves of the IPC
        // already trust each other on cookie match; logging it would
        // make crash dumps a credential.
        f.write_str("LaunchCookie(<redacted>)")
    }
}

/// RAII guard holding the advisory file lock on the launch-cookie file
/// for the lifetime of the first instance.
///
/// Dropped on graceful shutdown; the kernel auto-releases the lock on
/// process exit (including panics and `kill -9`), so the lock is also
/// a liveness signal.
pub struct LaunchLock {
    // The `'static` lifetime is a deliberate leak: this struct lives for
    // the whole process when held. `fd_lock::RwLock` owns the
    // `std::fs::File` and the guard borrows from it; leaking the
    // `RwLock` makes the borrow `'static`.
    _guard: FdRwLockWriteGuard<'static, File>,
}

pub enum CreatedOrRead {
    /// We acquired the exclusive lock and wrote the cookie.
    Created {
        lock: LaunchLock,
        cookie: LaunchCookie,
    },
    /// We couldn't write the cookie so we read it instead.
    Read { cookie: LaunchCookie },
}

/// Create or read the launch cookie.
///
/// - If we win the race we write a fresh random cookie under the
///   exclusive lock and return [`CreatedOrRead::Created`].
/// - If another instance already holds the lock we read its cookie out
///   of the file and return [`CreatedOrRead::Read`].
pub fn create_or_read() -> Result<CreatedOrRead> {
    let path = path()?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create `{}`", parent.display()))?;
    }

    let file = OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(&path)
        .with_context(|| format!("Failed to open launch cookie `{}`", path.display()))?;

    // Leak the `RwLock` so the guard's borrow is `'static`; the
    // first-instance state lives for the whole process either way.
    let lock: &'static mut FdRwLock<File> = Box::leak(Box::new(FdRwLock::new(file)));

    match lock.try_write() {
        Ok(mut guard) => {
            let cookie = LaunchCookie::random();
            guard
                .seek(SeekFrom::Start(0))
                .context("Failed to rewind launch cookie file")?;
            guard
                .set_len(0)
                .context("Failed to truncate launch cookie file")?;
            guard
                .write_all(cookie.as_bytes())
                .context("Failed to write launch cookie")?;
            guard
                .sync_data()
                .context("Failed to fsync launch cookie file")?;

            Ok(CreatedOrRead::Created {
                lock: LaunchLock { _guard: guard },
                cookie,
            })
        }
        Err(_) => {
            // Second instance: the process exits very shortly after
            // the hand-off handshake, so the `Box::leak`-ed
            // `FdRwLock` and its underlying file handle are reclaimed
            // by the OS without user-visible impact.
            let mut f = File::open(&path)
                .with_context(|| format!("Failed to open launch cookie `{}`", path.display()))?;
            let mut buf = [0u8; COOKIE_LEN];
            f.read_exact(&mut buf).with_context(|| {
                format!(
                    "Launch cookie at `{}` was shorter than {COOKIE_LEN} bytes — \
                     possible race with first-instance write",
                    path.display()
                )
            })?;

            Ok(CreatedOrRead::Read {
                cookie: LaunchCookie(buf),
            })
        }
    }
}

/// Per-user launch-cookie path.
///
/// Lives under `known_dirs::session()` so each Windows user / Linux account gets a
/// distinct file (and distinct first-instance scope).
fn path() -> Result<PathBuf> {
    let dir = known_dirs::session().context("No session directory available")?;
    Ok(dir.join("launch-cookie"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn partial_eq_is_byte_exact() {
        let a = LaunchCookie::new([1; 32]);
        assert_eq!(a, LaunchCookie::new([1; 32]));
        assert_ne!(a, LaunchCookie::new([0; 32]));

        let mut almost = [1u8; 32];
        almost[17] ^= 0x01;
        assert_ne!(a, LaunchCookie::new(almost));
    }

    #[test]
    fn debug_does_not_leak_bytes() {
        let s = format!("{:?}", LaunchCookie::new([0xab; 32]));
        assert!(!s.contains("ab"), "got: {s}");
        assert!(s.contains("<redacted>"));
    }
}
