//! Per-launch cookie + advisory file lock for GUI first-instance detection.
//!
//! The first GUI instance acquires an exclusive non-blocking advisory lock
//! on `<known_dirs::session()>/launch-cookie` and writes a fresh 32-byte
//! random cookie into it. The lock is held for the lifetime of the
//! process. Subsequent launches can't take the lock, so they read the
//! cookie out of the file and use it to authenticate IPC traffic to the
//! already-running instance.
//!
//! ## Why a cookie?
//!
//! The cookie binds an IPC connection to a specific *launch generation*.
//! After a graceful shutdown or a crash the kernel auto-releases the
//! file lock, a fresh launch becomes the new first instance, and the
//! cookie file is overwritten under the new exclusive lock. Any
//! connection from a process that read the stale cookie before the
//! crash-restart cycle is rejected.
//!
//! The cookie is **not** a same-user secret — a hostile same-user
//! process can read the file directly. The real identity check is the
//! pipe DACL on Windows (kernel-tracked package SID) and the socket
//! filesystem permissions on Linux. The cookie is the freshness glue
//! across launches.
//!
//! ## Why no cleanup on exit?
//!
//! The cookie file is intentionally **reused** across launches and never
//! deleted. Removal would create a window in which a fresh second
//! instance can't see the running first instance's cookie at all. The
//! mechanism we need — "the running first instance's identity" — is the
//! presence of an exclusive lock on a known-name file, which is exactly
//! what the kernel maintains for us as long as the process is alive.
//!
//! OS-level "delete on close" features (`FILE_FLAG_DELETE_ON_CLOSE` on
//! Windows, `O_TMPFILE` on Linux) would either remove the file before
//! the second instance can find it by name, or never give the file a
//! name in the first place — both break the read path. The current
//! design is fail-safe: a stale cookie file is harmless because every
//! first instance overwrites it under its own freshly-acquired lock.

use anyhow::{Context, Result, bail};
use fd_lock::{RwLock as FdRwLock, RwLockWriteGuard as FdRwLockWriteGuard};
use std::{
    fs::{File, OpenOptions},
    io::{ErrorKind, Read, Seek, SeekFrom, Write},
    path::PathBuf,
    time::Duration,
};

/// Wire size of the launch cookie. 256 bits of randomness; the field on
/// the IPC `ClientMsg` is `[u8; COOKIE_LEN]`.
pub const COOKIE_LEN: usize = 32;

/// 32-byte random cookie generated by the first instance on launch and
/// shared with subsequent instances via a user-private file. Wrapped in
/// a newtype so the validation site uses constant-time compare via
/// [`subtle::ConstantTimeEq`] rather than `==`.
#[derive(Clone, Copy)]
pub struct LaunchCookie([u8; COOKIE_LEN]);

impl LaunchCookie {
    /// Wraps a raw cookie byte array — used by tests and by the
    /// second-instance read path.
    pub fn new(bytes: [u8; COOKIE_LEN]) -> Self {
        Self(bytes)
    }

    /// Random cookie suitable for production use.
    pub fn random() -> Self {
        Self(rand::random())
    }

    pub fn as_bytes(&self) -> &[u8; COOKIE_LEN] {
        &self.0
    }

    /// Constant-time compare. The threat model doesn't actually expose
    /// timing oracles to a network attacker, but using `ConstantTimeEq`
    /// is cheap insurance against future changes.
    pub fn matches(&self, other: &[u8; COOKIE_LEN]) -> bool {
        use subtle::ConstantTimeEq as _;
        self.0.ct_eq(other).into()
    }
}

impl std::fmt::Debug for LaunchCookie {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Don't accidentally log the cookie. Both halves of the IPC
        // already trust each other on cookie match; logging it would
        // make crash dumps a credential.
        f.write_str("LaunchCookie(<redacted>)")
    }
}

/// RAII guard holding the advisory file lock on the launch-cookie file
/// for the lifetime of the first instance.
///
/// Dropped on graceful shutdown; the kernel auto-releases the lock on
/// process exit (including panics and `kill -9`), so the lock is also
/// a liveness signal.
pub struct LaunchLock {
    // The `'static` lifetime is a deliberate leak: this struct lives for
    // the whole process when held. `fd_lock::RwLock` owns the
    // `std::fs::File` and the guard borrows from it; leaking the
    // `RwLock` makes the borrow `'static`.
    _guard: FdRwLockWriteGuard<'static, File>,
}

/// Outcome of [`create_or_read`].
pub enum FirstInstance {
    /// We acquired the exclusive lock and are the running first
    /// instance. The `LaunchLock` must be held for the process
    /// lifetime; dropping it releases the lock and unblocks a
    /// subsequent first-instance check.
    Yes {
        lock: LaunchLock,
        cookie: LaunchCookie,
    },
    /// Another instance is alive and holds the lock; this is the
    /// cookie they wrote to the file. The caller is expected to send
    /// it on every IPC frame to the first instance and then exit.
    No { cookie: LaunchCookie },
}

/// Per-user launch-cookie path. Lives under
/// `known_dirs::session()` so each Windows user / Linux account gets a
/// distinct file (and distinct first-instance scope).
fn path() -> Result<PathBuf> {
    let dir = known_dirs::session().context("No session directory available")?;
    Ok(dir.join("launch-cookie"))
}

/// Tries to become the first GUI instance.
///
/// - If we win the race we write a fresh random cookie under the
///   exclusive lock and return [`FirstInstance::Yes`].
/// - If another instance already holds the lock we read its cookie out
///   of the file and return [`FirstInstance::No`].
pub fn create_or_read() -> Result<FirstInstance> {
    let path = path()?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create `{}`", parent.display()))?;
    }

    let file = OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(&path)
        .with_context(|| format!("Failed to open launch cookie `{}`", path.display()))?;

    // Leak the `RwLock` so the guard's borrow is `'static`; the
    // first-instance state lives for the whole process either way.
    let lock: &'static mut FdRwLock<File> = Box::leak(Box::new(FdRwLock::new(file)));

    match lock.try_write() {
        Ok(mut guard) => {
            let cookie = LaunchCookie::random();
            guard
                .seek(SeekFrom::Start(0))
                .context("Failed to rewind launch cookie file")?;
            guard
                .set_len(0)
                .context("Failed to truncate launch cookie file")?;
            guard
                .write_all(cookie.as_bytes())
                .context("Failed to write launch cookie")?;
            guard
                .sync_data()
                .context("Failed to fsync launch cookie file")?;
            Ok(FirstInstance::Yes {
                lock: LaunchLock { _guard: guard },
                cookie,
            })
        }
        Err(_) => {
            // Second instance: the process exits very shortly after
            // the hand-off handshake, so the `Box::leak`-ed
            // `FdRwLock` and its underlying file handle are reclaimed
            // by the OS without user-visible impact.
            //
            // We deliberately *don't* `drop(lock)` here. `lock` is a
            // `&'static mut FdRwLock<File>`, and `lock.try_write()`
            // above keeps that reference mutably borrowed across the
            // whole `match` expression — calling `drop` on it would
            // try to *move* it and fail to compile with "cannot move
            // out of `lock` because it is borrowed". The variable
            // simply falls out of scope at the end of this arm; the
            // leaked allocation is what we want.
            let cookie = read_cookie_with_retry(&path)?;
            Ok(FirstInstance::No { cookie })
        }
    }
}

/// Reads the 32-byte cookie out of the file, retrying briefly if the
/// file is shorter than expected.
///
/// There is a narrow race when the first instance has just acquired
/// the lock but hasn't finished its `write_all` + `sync_data` yet: a
/// second instance that fails its own `try_write` and immediately
/// reads will see fewer than 32 bytes. The lock is advisory so we
/// can't serialize the reader against the writer through the OS;
/// instead we retry on `UnexpectedEof` (`read_exact` short-read) with
/// a few-millisecond backoff. In practice the first-instance write is
/// a single 32-byte syscall that completes in tens of microseconds.
fn read_cookie_with_retry(path: &std::path::Path) -> Result<LaunchCookie> {
    let mut last_err: Option<anyhow::Error> = None;
    for backoff_ms in [0u64, 2, 5, 10, 25] {
        if backoff_ms > 0 {
            std::thread::sleep(Duration::from_millis(backoff_ms));
        }
        let mut f = File::open(path)
            .with_context(|| format!("Failed to open launch cookie `{}`", path.display()))?;
        let mut buf = [0u8; COOKIE_LEN];
        match f.read_exact(&mut buf) {
            Ok(()) => return Ok(LaunchCookie::new(buf)),
            Err(e) if e.kind() == ErrorKind::UnexpectedEof => {
                last_err = Some(anyhow::Error::new(e).context(format!(
                    "Launch cookie at `{}` was shorter than {COOKIE_LEN} bytes",
                    path.display()
                )));
                continue;
            }
            Err(e) => bail!(anyhow::Error::new(e).context("Failed to read launch cookie")),
        }
    }
    Err(last_err.unwrap_or_else(|| {
        anyhow::anyhow!(
            "Launch cookie at `{}` did not reach {COOKIE_LEN} bytes after retries",
            path.display()
        )
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn matches_is_byte_exact() {
        let a = LaunchCookie::new([1; 32]);
        assert!(a.matches(&[1; 32]));
        assert!(!a.matches(&[0; 32]));

        let mut almost = [1u8; 32];
        almost[17] ^= 0x01;
        assert!(!a.matches(&almost));
    }

    #[test]
    fn debug_does_not_leak_bytes() {
        let s = format!("{:?}", LaunchCookie::new([0xab; 32]));
        assert!(!s.contains("ab"), "got: {s}");
        assert!(s.contains("<redacted>"));
    }
}
