# Meant to be used with docker-compose.yml
services:
  client:
    build:
      target: runtime
    volumes:
      - ./rust/target/x86_64-unknown-linux-musl/debug/firezone-linux-client:/bin/firezone-linux-client

  gateway:
    build:
      target: runtime
    volumes:
      - ./rust/target/x86_64-unknown-linux-musl/debug/firezone-gateway:/bin/firezone-gateway

  relay:
    build:
      target: runtime
    volumes:
      - ./rust/target/x86_64-unknown-linux-musl/debug/firezone-relay:/bin/firezone-relay
  
