[package]
name = "connlib-core-affinity"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
core_affinity = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
