[package]
name = "connlib-core-affinity"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[lib]
path = "lib.rs"

[target.'cfg(not(any(target_os = "macos", target_os = "ios")))'.dependencies]
core_affinity = { workspace = true }

[dependencies]
tracing = { workspace = true }

[lints]
workspace = true
