[package]
name = "phoenix-channel"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
backoff = { workspace = true }
base64 = { workspace = true }
firezone-logging = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
os_info = { workspace = true }
rand_core = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
socket-factory = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["net", "time"] }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["std", "v4"] }

[target.'cfg(system_certs)'.dependencies]
tokio-tungstenite = { workspace = true, features = ["rustls-tls-native-roots"] }

[target.'cfg(not(system_certs))'.dependencies]
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }

[target.'cfg(target_os = "windows")'.dependencies]
hostname = "0.4.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "tracing"] }

[lints]
workspace = true
