# Builds a Postgres image with needed extensions and modules for local development

# Install wal2json
ARG POSTGRES_VERSION=15
FROM postgres:${POSTGRES_VERSION}-alpine AS builder
RUN apk add --no-cache \
  build-base \
  git \
  llvm \
  clang \
  curl
ARG WAL2JSON_VERSION=2_6
RUN curl -fssL https://github.com/eulerto/wal2json/archive/refs/tags/wal2json_${WAL2JSON_VERSION}.tar.gz | tar -xzf - -C /tmp --strip-components=1
WORKDIR /tmp
RUN USE_PGXS=1 make && make install

# Prepare final image
FROM postgres:${POSTGRES_VERSION}-alpine
COPY --from=builder /tmp/wal2json.so /usr/local/lib/postgresql/
