[package]
name = "x509-claims"
version = "0.1.0"
edition = { workspace = true }
authors = ["Firezone, Inc."]
license = { workspace = true }

[dependencies]
base64 = { workspace = true, features = ["std"] }
sha2 = { workspace = true }
uuid = { workspace = true }
x509-parser = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
rcgen = { workspace = true }

[[bench]]
name = "parse_certificate"
harness = false

[lints]
workspace = true
