[package]
name = "uniffi-bindgen"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "uniffi-bindgen"
path = "main.rs"

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[lints]
workspace = true
