[package]
name = "etherparse-ext"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
etherparse = { workspace = true, default-features = false }

[lints]
workspace = true
