name: "GHCR docker registry login"
description: "Login to the GitHub container registry"

inputs:
  github_token:
    description: "GitHub token to use for authentication"
    required: true

outputs:
  registry:
    description: "The full name of the registry we logged into"
    value: ${{ format('ghcr.io') }}

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
