name: "GHCR docker registry login"
description: "Login to the GitHub container registry"

inputs:
  github_token:
    description: "GitHub token to use for authentication"
    required: true

outputs:
  registry:
    description: "The full name of the registry we logged into"
    value: ${{ format('ghcr.io') }}

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
