# From https://tauri.app/v1/guides/getting-started/prerequisites
name: "Setup Android"
description: "Sets up the dependencies for building our Android app"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-rust
      with:
        targets: armv7-linux-androideabi aarch64-linux-android x86_64-linux-android i686-linux-android

    - uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

    - uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2

    - name: Install NDK
      run: sdkmanager "ndk;28.1.13356709" # Must match `kotlin/android/app/build.gradle.kts`
      shell: bash

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

    - run: touch local.properties
      shell: bash
