# From https://tauri.app/v1/guides/getting-started/prerequisites
name: "Setup Android"
description: "Sets up the dependencies for building our Android app"
inputs:
  sccache_azure_connection_string:
    description: "Azure connection string for sccache"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-rust
      with:
        sccache_azure_connection_string: ${{ inputs.sccache_azure_connection_string }}

    - uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0
      with:
        working_directory: kotlin/android

    - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

    - uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
      with:
        # By default tools and platform-tools are installed, which we don't use currently
        # These consume lots of disk space
        packages: ""

    - name: Install NDK
      run: sdkmanager "ndk;28.1.13356709" # Must match `kotlin/android/app/build.gradle.kts`
      shell: bash

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

    - run: touch local.properties
      shell: bash
