# From https://tauri.app/v1/guides/getting-started/prerequisites
name: "Setup Android"
description: "Sets up the dependencies for building our Android app"
runs:
  using: "composite"
  steps:
    - uses: marocchino/tool-versions-action@18a164fa2b0db1cc1edf7305fcb17ace36d1c306 # v1.2.0
      with:
        path: kotlin/android/.tool-versions

    - uses: ./.github/actions/setup-rust-stable
      with:
        targets: armv7-linux-androideabi aarch64-linux-android x86_64-linux-android i686-linux-android

    - uses: ./.github/actions/setup-rust-sccache

    - uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

    - uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
      with:
        # By default tools and platform-tools are installed, which we don't use currently
        # These consume lots of disk space
        packages: ""

    - name: Install NDK
      run: sdkmanager "ndk;28.1.13356709" # Must match `kotlin/android/app/build.gradle.kts`
      shell: bash

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

    - run: touch local.properties
      shell: bash
