# From https://tauri.app/v1/guides/getting-started/prerequisites
name: "Setup Android"
description: "Sets up the dependencies for building our Android app"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-rust
      with:
        targets: armv7-linux-androideabi aarch64-linux-android x86_64-linux-android i686-linux-android

    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0

    - uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
      with:
        # By default tools and platform-tools are installed, which we don't use currently
        # These consume lots of disk space
        packages: ""

    - name: Install NDK
      run: sdkmanager "ndk;28.1.13356709" # Must match `kotlin/android/app/build.gradle.kts`
      shell: bash

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0

    - run: touch local.properties
      shell: bash
