---
name: "Setup Rust sccache"
description: "Sets up caching for Rust via sccache"
runs:
  using: "composite"
  steps:
    - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

    - name: Cache registry
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      with:
        workspaces: rust
        cache-targets: false
        save-if: ${{ github.ref == 'refs/heads/main' }} # Only save on main

    - name: Configure sccache environment
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
        echo "RUSTC_WRAPPER=$SCCACHE_PATH" >> "$GITHUB_ENV"

    - name: Start sccache
      run: ./scripts/retry.sh $SCCACHE_PATH --start-server
      continue-on-error: true
      shell: bash
      env:
        SCCACHE_CONF: ".github/actions/setup-rust-sccache/sccache.toml"
