#!/usr/bin/env bash

set -euo pipefail

OLD_SERVICE_NAME="firezone-client-ipc"

sudo systemctl disable "$OLD_SERVICE_NAME" >/dev/null 2>&1 || true
sudo systemctl stop "$OLD_SERVICE_NAME" >/dev/null 2>&1 || true
