#!/usr/bin/env bash

set -euo pipefail

SERVICE_NAME="firezone-client-tunnel"

# `rpm` calls `prerm` of the old package _after_ it has installed the new package.
# The first parameter indicates, how many other instances of the package are still installed.
# If we are being upgraded, this will be 1.
# In that case, we do _not_ want to stop the systemd service, otherwise the user will be greeted with "Firezone Tunnel service is not running".
if [ "$1" == 1 ]; then
    exit 0
fi

sudo systemctl disable "$SERVICE_NAME"
sudo systemctl stop "$SERVICE_NAME"
