# Dockerfile for building RPM packages for CentOS
# CentOS Stream 9
FROM quay.io/centos/centos

RUN yum install -y rpm-build systemd-rpm-macros && yum clean all

RUN mkdir -p /root/rpmbuild
WORKDIR /root/rpmbuild
