#!/bin/sh

# Perform necessary post-installation steps

capture () {
  if type curl > /dev/null; then
    host=`hostname -f`
    curl -s -XPOST \
      -H 'Content-Type: application/json' \
      -d "{
        \"api_key\": \"phc_ubuPhiqqjMdedpmbWpG2Ak3axqv5eMVhFDNBaXl9UZK\",
        \"event\": \"postinst\",
        \"properties\": {
          \"distinct_id\": \"$host\"
        }
      }" \
      https://telemetry.firez.one/capture/ > /dev/null
  fi
}
if [ -e /opt/firezone/.disable-telemetry ]; then
  export TELEMETRY_ENABLED=false
fi
if [ "$TELEMETRY_ENABLED" != "false" ]; then
  capture || true
fi

# Symlink ctl commands
DEST_DIR=/opt/firezone

${DEST_DIR}/embedded/bin/symlink_ctl_cmds
