#!/bin/sh

# Perform necessary post-installation steps

capture () {
  if type curl > /dev/null; then
    if [ -e /opt/firezone/sv/phoenix/env/TELEMETRY_ID ]; then
      telemetry_id=`cat /opt/firezone/sv/phoenix/env/TELEMETRY_ID`
      curl -s -XPOST \
        -H 'Content-Type: application/json' \
        -d "{
          \"api_key\": \"phc_ubuPhiqqjMdedpmbWpG2Ak3axqv5eMVhFDNBaXl9UZK\",
          \"event\": \"postinst\",
          \"properties\": {
            \"distinct_id\": \"$telemetry_id\"
          }
        }" \
        https://telemetry.firez.one/capture/ > /dev/null
    fi
  fi
}
if [ ! -e /opt/firezone/.disable-telemetry ]; then
  capture || true
fi

# Symlink ctl commands
DEST_DIR=/opt/firezone

${DEST_DIR}/embedded/bin/symlink_ctl_cmds
