#!/bin/sh
set -e
#
# Perform necessary firezone removal steps
# after package is uninstalled.
#

capture () {
  if type curl > /dev/null; then
    if [ -e /var/opt/firezone/cache/telemetry_id ]; then
      telemetry_id=`cat /var/opt/firezone/cache/telemetry_id`
      if [ ! -z "$telemetry_id" ]; then
        curl -s -XPOST \
          -m 5 \
          -H 'Content-Type: application/json' \
          -d "{
            \"api_key\": \"phc_ubuPhiqqjMdedpmbWpG2Ak3axqv5eMVhFDNBaXl9UZK\",
            \"event\": \"postrm\",
            \"properties\": {
              \"distinct_id\": \"$telemetry_id\"
            }
          }" \
          https://telemetry.firez.one/capture/ > /dev/null
      fi
    fi
  fi
}
if [ ! -e /var/opt/firezone/.disable_telemetry ]; then
  capture || true
fi

echo "firezone has been uninstalled!"

exit 0
