#!/bin/sh
set -e
#
# Perform necessary firezone removal steps
# after package is uninstalled.
#

capture () {
  if type curl > /dev/null; then
    host=`hostname -f`
    curl -s -XPOST \
      -H 'Content-Type: application/json' \
      -d "{
        \"api_key\": \"phc_ubuPhiqqjMdedpmbWpG2Ak3axqv5eMVhFDNBaXl9UZK\",
        \"event\": \"postrm\",
        \"properties\": {
          \"distinct_id\": \"$host\"
        }
      }" \
      https://telemetry.firez.one/capture/ > /dev/null
  fi
}
if [ -e /opt/firezone/.disable-telemetry ]; then
  export TELEMETRY_ENABLED=false
fi
if [ "$TELEMETRY_ENABLED" != "false" ]; then
  capture || true
fi

echo "firezone has been uninstalled!"

exit 0
