#!/bin/sh
set -e
#
# Perform necessary firezone setup steps
# before package is installed.
#

capture () {
  if type curl > /dev/null; then
    if [ -e /opt/firezone/sv/phoenix/env/TELEMETRY_ID ]; then
      telemetry_id=`cat /opt/firezone/sv/phoenix/env/TELEMETRY_ID`
      curl -s -XPOST \
        -H 'Content-Type: application/json' \
        -d "{
          \"api_key\": \"phc_ubuPhiqqjMdedpmbWpG2Ak3axqv5eMVhFDNBaXl9UZK\",
          \"event\": \"preinst\",
          \"properties\": {
            \"distinct_id\": \"$telemetry_id\"
          }
        }" \
        https://telemetry.firez.one/capture/ > /dev/null
    fi
  fi
}
if [ ! -e /opt/firezone/.disable-telemetry ]; then
  capture || true
fi

echo "You're about to install firezone!"
