#!/bin/sh
set -e
#
# Perform necessary firezone setup steps
# before package is installed.
#

kernelCheck() {
  major=`uname -r | cut -d'.' -f1`
  if [ "$major" -lt "5" ]; then
    echo "################################################################################"
    echo "# ERROR: Kernel version `uname -r` is not supported. Firezone requires         #"
    echo "# kernel >= 5 or higher. See our listed of supported platforms for more        #"
    echo "# information: https://docs.firez.one/docs/deploy/supported-platforms/         #"
    echo "################################################################################"
    exit
  fi
}

capture () {
  if type curl > /dev/null; then
    if [ -e /var/opt/firezone/cache/telemetry_id ]; then
      telemetry_id=`cat /var/opt/firezone/cache/telemetry_id`
      if [ ! -z "$telemetry_id" ]; then
        curl -s -XPOST \
          -H 'Content-Type: application/json' \
          -d "{
            \"api_key\": \"phc_ubuPhiqqjMdedpmbWpG2Ak3axqv5eMVhFDNBaXl9UZK\",
            \"event\": \"preinst\",
            \"properties\": {
              \"distinct_id\": \"$telemetry_id\"
            }
          }" \
          https://telemetry.firez.one/capture/ > /dev/null
      fi
    fi
  fi
}
if [ ! -e /var/opt/firezone/.disable_telemetry ]; then
  capture || true
fi

echo "You're about to install firezone!"
kernelCheck
