#!/bin/sh
#
# Perform necessary firezone setup steps
# prior to uninstalling package.
#

PROGNAME=`basename $0`

capture () {
  if type curl > /dev/null; then
    host=`hostname -f`
    curl -s -XPOST \
      -H 'Content-Type: application/json' \
      -d "{
        \"api_key\": \"phc_ubuPhiqqjMdedpmbWpG2Ak3axqv5eMVhFDNBaXl9UZK\",
        \"event\": \"prerm\",
        \"properties\": {
          \"distinct_id\": \"$host\"
        }
      }" \
      https://telemetry.firez.one/capture/ > /dev/null
  fi
}
if [ -e /opt/firezone/.disable-telemetry ]; then
  export TELEMETRY_ENABLED=false
fi
if [ "$TELEMETRY_ENABLED" != "false" ]; then
  capture || true
fi

/opt/firezone/embedded/sbin/nft delete table inet firezone || true

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

exit 0
