[package]
name = "dns-types"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
domain = { version = "0.10", features = ["serde"] } # Not a workspace dependency because we don't want any other crates to depend on it.
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
