name: "Upload GUI artifact"
description: "Uploads an exe / package / installer for the Firezone GUI client"
inputs:
  base:
    description: "Base file name, e.g. `firezone-linux-gui-client_amd64.deb`"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name:
        path: |
          ${{ github.workspace }}/rust/gui-client/${{ inputs.base }}
          ${{ github.workspace }}/rust/gui-client/${{ inputs.base }}.sha256sum.txt
