[package]
name = "completion-io"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
backoff = { workspace = true }
phoenix-channel = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rustls = { workspace = true }
tunnel-bypass-resolver = { workspace = true }
bufferpool = { workspace = true }
client-shared = { workspace = true }
futures = { workspace = true }
ip-packet = { workspace = true }
libc = { workspace = true }
socket-factory = { workspace = true }
socket2 = { workspace = true, features = ["all"] }
quinn-udp = { workspace = true }
tun = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "sync"] }
tunnel = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
compio = { workspace = true, features = ["io-uring"] }

[target.'cfg(target_os = "android")'.dependencies]
compio = { workspace = true, features = ["polling"] }

[target.'cfg(target_os = "windows")'.dependencies]
compio = { workspace = true, features = ["iocp-wait-packet"] }
wintun = "0.5.1"
windows-sys = { version = "0.61", features = ["Win32_Networking_WinSock", "Win32_System_Threading", "Win32_System_IO"] }

[lints]
workspace = true
