[package]
name = "fuzz-runner"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
afl = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
seeded-rng = { workspace = true }

[lints]
workspace = true
