#!/usr/bin/env bash
# Usage: dpkg will call this after installing our files

set -euo pipefail

OLD_SERVICE_NAME="firezone-client-ipc"
SERVICE_NAME="firezone-tunnel-service"

sudo systemctl disable "$OLD_SERVICE_NAME" || true
sudo systemctl stop "$OLD_SERVICE_NAME" || true

sudo systemctl disable "$SERVICE_NAME"
sudo systemctl stop "$SERVICE_NAME"
