#!/usr/bin/env bash
# Usage: dpkg will call this after installing our files

set -euo pipefail

SERVICE_NAME="firezone-tunnel-service"

sudo systemctl disable "$SERVICE_NAME"
sudo systemctl stop "$SERVICE_NAME"
