[package]
name = "x509-keystore"
version = "0.1.0"
edition = { workspace = true }
authors = ["Firezone, Inc."]
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
x509-claims = { workspace = true }
x509-credential = { workspace = true }

[lints]
workspace = true
