[package]
name = "ebpf-shared"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[features]
std = ["aya"]

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true, optional = true }
