[package]
name = "ebpf-shared"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[features]
std = ["aya"]

[dependencies]
derive_more = { workspace = true, features = ["from"] }

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true, optional = true }
