---
name: "Setup Rust"
description: "Sets up the correct Rust version"

outputs:
  bench-packages:
    description: Benchmarkable packages for the current OS
    value: ${{
      (runner.os == 'Linux' && '--help') ||
      (runner.os == 'macOS' && '--help') ||
      (runner.os == 'Windows' && '-p bin-shared') }}
  compile-packages:
    description: Compilable packages for the current OS
    value: ${{
      (runner.os == 'Linux' && '--workspace') ||
      (runner.os == 'macOS' && '--workspace') ||
      (runner.os == 'Windows' && '--workspace --exclude ebpf-turn-router --exclude client-ffi') }}
  test-packages:
    description: Testable packages for the current OS
    value: ${{
      (runner.os == 'Linux' && '--workspace') ||
      (runner.os == 'macOS' && '--workspace --exclude bin-shared --exclude firezone-gui-client') ||
      (runner.os == 'Windows' && '--workspace --exclude client-ffi') }}

runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      id: toolchain-1
      continue-on-error: true
      with:
        components: rustfmt,clippy,llvm-tools-preview
        cache: false # We explicitly configure caching somewhere else.
        rust-src-dir: rust/

    - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      if: ${{ steps.toolchain-1.outcome == 'failure' }}
      continue-on-error: true
      id: toolchain-2
      with:
        components: rustfmt,clippy,llvm-tools-preview
        cache: false # We explicitly configure caching somewhere else.
        rust-src-dir: rust/

    - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      if: ${{ steps.toolchain-2.outcome == 'failure' }}
      with:
        components: rustfmt,clippy,llvm-tools-preview
        cache: false # We explicitly configure caching somewhere else.
        rust-src-dir: rust/
