FROM rust:latest as builder
WORKDIR build
COPY . .
ARG CARGO_HOME=./.cargo
RUN cargo build -r -p e2e-client && \
	cp ./target/release/e2e-client /bin/e2e-client

FROM linuxserver/wireguard:latest
RUN apt-get update && \
	apt-get install -y lsof && \
	rm -Rf \
		/tmp/* \
		/var/lib/apt/lists/* \
		/var/tmp/*

WORKDIR /usr/e2e/
COPY --from=builder /bin/e2e-client .
HEALTHCHECK --start-period=20s --interval=10s --retries=5 --timeout=5s \
	CMD lsof -n -P -a -i:9090 -sTCP:listen
CMD ["/usr/e2e/e2e-client"]
