ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG PKG_DIR

# Copy shared files
COPY pkg/rpm_shared/rpmbuild rpmbuild
RUN rsync -avz pkg/skel/* rpmbuild/BUILDROOT/$PKG_DIR/
RUN rsync -az _build/prod/rel/firezone/* rpmbuild/BUILDROOT/$PKG_DIR/usr/lib/firezone/
RUN mkdir -p rpmbuild/BUILDROOT/$PKG_DIR/usr/bin
RUN cd rpmbuild/BUILDROOT/$PKG_DIR/usr/bin && ln -s ../lib/firezone/bin/firezone
RUN rpmbuild -bb rpmbuild/SPECS/firezone.spec
