defmodule Portal.Repo.Migrations.AddFlowActivitiesConnectivityType do
  use Ecto.Migration

  def change do
    # It's safe to delete now gateways don't send those metrics yet,
    # and only data that can be inserted is generated by testing
    execute("DELETE FROM flow_activities;")

    alter table(:flow_activities) do
      add(:connectivity_type, :string, null: false)
    end
  end
end
