name: Sync APT repository metadata
run-name: Triggered by ${{ github.actor }}
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: "create-apt-repository" # Unique group name to force only a single job at a time.
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write # OIDC auth for Azure Storage

jobs:
  create-apt-repository-metadata:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-azure-cli

      - name: Azure login (OIDC)
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.AZURE_ARTIFACTS_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_ARTIFACTS_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_ARTIFACTS_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - uses: ./.github/actions/setup-gpg
        id: setup-gpg
        with:
          key: ${{ secrets.APT_REPOSITORY_GPG_KEY }}
          email: packages@firezone.dev

      - run: scripts/sync-apt.sh
        env:
          AZURE_STORAGE_ACCOUNT: firezoneartifacts
          GPG_KEY_ID: ${{ steps.setup-gpg.outputs.key_id }}
