name: Build control plane
run-name: Triggered from ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_call:
    inputs:
      sha:
        required: false
        type: string
        default: ${{ github.sha }}

permissions:
  id-token: write # OIDC auth
  packages: write # push Docker images to GHCR

jobs:
  control-plane:
    name: ${{ matrix.image_name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: ${{ github.event_name == 'merge_group' }}
      matrix:
        include:
          - image_name: portal
            target: runtime
            build-args: |
              APPLICATION_NAME=portal
              GIT_SHA=${{ inputs.sha }}
          - image_name: elixir
            target: compiler
            build-args: |
              APPLICATION_NAME=portal
              GIT_SHA=${{ inputs.sha }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - uses: ./.github/actions/ghcr-docker-login
        id: login
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ steps.login.outputs.registry }}/firezone/${{matrix.image_name }}
          tags: |
            type=raw,value=${{ inputs.sha }}
      - name: Sanitize github.ref_name
        run: |
          # `ref_name` contains `/`, '_' or '=' which is not a valid docker image tag
          REF="${{ github.ref_name }}"
          CACHE_TAG="${REF//[\/_=]/-}"
          echo "CACHE_TAG=$CACHE_TAG" >> "$GITHUB_ENV"
      # PRs & non-main branches: read-only cache
      - name: Build and push control plane images (read-only cache)
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          build-args: ${{ matrix.build-args }}
          target: ${{ matrix.target }}
          context: elixir
          cache-from: |
            type=gha,scope=${{ matrix.image_name }}:${{ env.CACHE_TAG }}
            type=gha,scope=${{ matrix.image_name }}:main
          # no cache-to here -> read-only
          push: true
          tags: |
            ${{ steps.login.outputs.registry }}/firezone/${{ matrix.image_name }}:${{ inputs.sha }}
            ${{ steps.login.outputs.registry }}/firezone/${{ matrix.image_name }}:${{ env.CACHE_TAG }}
          labels: |
            org.opencontainers.image.revision=${{ inputs.sha }}

      # main: read/write cache
      - name: Build and push control plane images (read/write cache)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          build-args: ${{ matrix.build-args }}
          target: ${{ matrix.target }}
          context: elixir
          cache-from: |
            type=gha,scope=${{ matrix.image_name }}:${{ env.CACHE_TAG }}
            type=gha,scope=${{ matrix.image_name }}:main
          cache-to: |
            type=gha,scope=${{ matrix.image_name }}:${{ env.CACHE_TAG }},mode=max,ignore-error=true
          push: true
          tags: |
            ${{ steps.login.outputs.registry }}/firezone/${{ matrix.image_name }}:${{ inputs.sha }}
            ${{ steps.login.outputs.registry }}/firezone/${{ matrix.image_name }}:${{ env.CACHE_TAG }}
          labels: |
            org.opencontainers.image.revision=${{ inputs.sha }}
