name: Elixir
on:
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./elixir
    permissions:
      checks: write # dorny/test-reporter
    env:
      MIX_ENV: test
      POSTGRES_HOST: localhost
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: chetan/git-restore-mtime-action@d186aca54f8760da4dec55313195e51ed3ebb0b3 # v2.3
      - uses: ./.github/actions/setup-postgres
      - uses: ./.github/actions/setup-elixir
        with:
          mix_env: ${{ env.MIX_ENV }}

      - name: Compile Application
        run: mix compile --warnings-as-errors

      - name: Setup Database
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run Tests with Coverage
        env:
          E2E_DEFAULT_WAIT_SECONDS: 20
          CI_ASSERT_RECEIVE_TIMEOUT_MS: 250
        run: mix coveralls.lcov

      - name: Test Report
        if: github.event.pull_request.head.repo.full_name == github.repository && (success() || failure())
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        with:
          name: Elixir Unit Test Report
          path: elixir/_build/test/lib/*/test-junit-report.xml
          reporter: java-junit

      - uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: elixir/cover/lcov.info
          format: lcov
          flag-name: portal
          parallel: true
          fail-on-error: false

  type-check:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./elixir
    env:
      # We need to set MIX_ENV to dev to make sure that we won't type-check our test helpers
      MIX_ENV: dev
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: chetan/git-restore-mtime-action@d186aca54f8760da4dec55313195e51ed3ebb0b3 # v2.3
      - uses: ./.github/actions/setup-elixir
        id: setup-beam
        with:
          mix_env: ${{ env.MIX_ENV }}

      - name: Compile Application
        run: mix compile --warnings-as-errors

      - name: Create PLTs
        run: mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer --format dialyxir

  static-analysis:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./elixir
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: chetan/git-restore-mtime-action@d186aca54f8760da4dec55313195e51ed3ebb0b3 # v2.3
      - uses: ./.github/actions/setup-elixir
        with:
          mix_env: ${{ env.MIX_ENV }}

      - name: Compile Application
        run: mix compile --force --warnings-as-errors

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Check For Retired Packages
        run: mix hex.audit

      - name: Check For Vulnerable Packages
        run: mix deps.audit

      - name: Run Sobelow vulnerability scanner
        working-directory: ./elixir
        run: mix sobelow --skip --exit

      - name: Run Credo
        run: mix credo --strict

      - name: Check for unused deps
        run: mix deps.unlock --check-unused

      - name: Validate OpenAPI spec
        run: |
          mix openapi.spec.yaml --spec PortalAPI.ApiSpec
          result=$(curl --fail --show-error --silent \
            --max-time 10 \
            --retry 3 \
            --retry-delay 1 \
            --retry-connrefused \
            --data-binary @openapi.yaml \
            -H 'Content-Type:application/yaml' \
            https://validator.swagger.io/validator/debug)
          echo "$result"
          echo "$result" | jq -e '.schemaValidationMessages | length == 0'
