name: Create publish PR
on:
  release:
    types:
      - published

jobs:
  create_publish_pr:
    name: Create publish PR ${{ matrix.component }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - android-client
          - apple-client
          - gateway
          - gui-client
          - headless-client
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_PR_BOT_GITHUB_TOKEN }}

      - id: Create PR
        if: ${{ startsWith(github.event.release.name, matrix.component) }}
        run: |
          # Extract version from release name
          version=${{ github.event.release.name }}
          version=${version#${{ matrix.component }}-}

          # Configure local git instance
          git config --local user.email "github-bot@firezone.dev"
          git config --local user.name "Firezone Bot"

          # Create the PR
          scripts/create-publish-pr.sh ${{ matrix.component }} $version
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PR_BOT_GITHUB_TOKEN }}
