name: Publish to WinGet
on:
  release:
    types:
      - published

jobs:
  publish_clients:
    name: Publish ${{ matrix.identifier }} to winget
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - identifier: Firezone.Client.GUI
            tag_prefix: gui-client
          - identifier: Firezone.Client.Headless
            tag_prefix: headless-client
    if: ${{ startsWith(github.event.release.name, matrix.tag_prefix) }}
    steps:
      - id: get-version
        run: |
          version=${{ github.event.release.name }}
          version=${version#${{ matrix.tag_prefix }}-}
          echo "version=$version" >> $GITHUB_OUTPUT
        shell: bash
      - uses: vedantmgoyal9/winget-releaser@19e706d4c9121098010096f9c495a70a7518b30f # main
        with:
          identifier: ${{ matrix.identifier }}
          version: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
          release-notes-url: https://firezone.dev/changelog
